# Generated by Django 2.2.28 on 2023-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('prep_time', models.IntegerField(blank=True, null=True)),
                ('cook_time', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
